export const ADD_ENTITY_TO_REGISTRY = 'ADD_ENTITY_TO_REGISTRY';
export const ADD_ENTITY_ENTRIES = 'ADD_ENTITY_ENTRIES';
export const UPDATE_CURRENT_DISPLAY_ENTITY = 'UPDATE_CURRENT_DISPLAY_ENTITY';
export const UPDATE_PAGINATION = 'UPDATE_PAGINATION';
export const UPDATE_LINKS = 'UPDATE_LINKS';
export const UPDATE_META = 'UPDATE_META';
export const UPDATE_LOADING_INDICATOR = 'UPDATE_LOADING_INDICATOR';